Cardápio/src/CárdapioV3_Tunado/CárdapioV3_Tunado/Controllers/CardapioController.cs
using CárdapioV3_Tunado.DAL;
using CárdapioV3_Tunado.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CárdapioV3_Tunado.Controllers
{
    public class CardapioController : Controller
    {
        ListCategoriaProduto cardapio2 = new ListCategoriaProduto();
        CardapioDAO cardapio = new CardapioDAO();
        EmpresaDAO empresa = new EmpresaDAO();

        
        public IActionResult Index(int idEmpresa)
        {
            if (User.Identity?.Name != null)
            {
                idEmpresa = int.Parse(User.Identity!.Name);
            }
            List<CategoriaProdutoView> lista = cardapio.getTodosProdutosbyEmpresa(idEmpresa);
            List<CategoriaProdutoView> listaCategoria = cardapio.getTodasCategoriasbyEmpresa(idEmpresa);


            try
            {
                var emp = empresa.getTodasEmpresas().First(x => x.EmpresaID == lista.First().EmpresaID);



                lista = lista.Select(x =>
                {
                    x.Telefone = emp.Telefone;
                    return x;
                }).ToList();
                listaCategoria.Select(x =>
                {
                    x.Telefone = emp.Telefone;
                    return x;
                }).ToList();





                lista = lista.Select(x =>
                {
                    x.FotoEmpresa = emp.FotoEmpresa;
                    return x;
                }).ToList();
                listaCategoria.Select(x =>
                {
                    x.FotoEmpresa = emp.FotoEmpresa;
                    return x;
                }).ToList();

                 lista = lista.Select(x =>
                {
                    x.PedID = emp.PedID;
                    return x;
                }).ToList();
                listaCategoria.Select(x =>
                {
                    x.PedID = emp.PedID;
                    return x;
                }).ToList();

                lista = lista.Select(x =>
                {
                    x.PedDataPedido = emp.PedDataPedido;
                    return x;
                }).ToList();
                listaCategoria.Select(x =>
                {
                    x.PedDataPedido = emp.PedDataPedido;
                    return x;
                }).ToList();

                lista = lista.Select(x =>
                {
                    x.NomeEmpresa = emp.NomeEmpresa;
                    return x;
                }).ToList();
                listaCategoria.Select(x =>
                {
                    x.NomeEmpresa = emp.NomeEmpresa;
                    return x;
                }).ToList();



                ViewBag.Empresaid = idEmpresa;



                lista = lista.Select(x =>
                {
                    x.Taxa = emp.taxaEmpresa;
                    return x;
                }).ToList();
                listaCategoria.Select(x =>
                {
                    x.Taxa = emp.taxaEmpresa;
                    return x;
                }).ToList();

                var listas = new ListCategoriaProduto
                {
                    Lista1 = lista,
                    Lista2 = listaCategoria
                };

                ViewBag.EmpresaID = emp.EmpresaID;
                return View(listas);
            }
            catch (Exception ex)
            {

                return RedirectToAction("Logar", "Empresa");
            }
           
        }





        //crud
        //create
        [HttpGet]
        public IActionResult create()
        {
            return View();

        }

        [HttpPost]
        public IActionResult create(string Nome, string Descricao, double preco, int Categoria)
        {
            CategoriaProdutoView NovoProduto = new CategoriaProdutoView();
            NovoProduto.DescricaoProduto = Descricao;
            NovoProduto.NomeProduto = Nome;
            NovoProduto.PrecoProduto = preco;
            NovoProduto.CategoriaProduto = Categoria;
            cardapio.InsertProdutos(NovoProduto);
            return RedirectToAction("Index");

        }
        //atualizar

        [HttpGet]
        public IActionResult Atualizar(int id)
        {
            ViewBag.ProdutoAtualizar = cardapio.getTodosProdutos().Where(x => x.ProID == id).FirstOrDefault();
            return View();
        }

        [HttpPost]
        public IActionResult Atualizar(string codigo, string nome, string descricao, double preco, int CategoriaProduto)
        {

            CategoriaProdutoView AtualizarProduto = new CategoriaProdutoView();
            AtualizarProduto.ProID = Convert.ToInt32(codigo);
            AtualizarProduto.NomeProduto = nome;
            AtualizarProduto.DescricaoProduto = descricao;            
            AtualizarProduto.PrecoProduto = preco;
            AtualizarProduto.CategoriaProduto = CategoriaProduto;
            cardapio.UptdateProdutos(AtualizarProduto);

            return RedirectToAction("Index");
        }
        //apagar
        [HttpGet]
        public IActionResult Apagar(string id)
        {

            CategoriaProdutoView apagarproduto = new CategoriaProdutoView();
            apagarproduto.ProID = Convert.ToInt32(id);
            cardapio.ApagarProdutos(apagarproduto);

            return RedirectToAction("Index");
        }
    }
}

Cardápio/src/CárdapioV3_Tunado/CárdapioV3_Tunado/Controllers/CategoriaController.cs
using CárdapioV3_Tunado.DAL;
using CárdapioV3_Tunado.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CárdapioV3_Tunado.Controllers
{
    [Authorize(Roles = "MASTER")]
    public class CategoriaController : Controller
    {
        CategoriaDAO categoria = new CategoriaDAO();

        public IActionResult Index()
        {
            ViewBag.listaCategorias = categoria.getTodasCategorias();
            return View();
        }

        //create
        [HttpGet]
        public IActionResult create()
        {
            return View();

        }

        [HttpPost]
        public IActionResult create(string NomeCategoria, string CategoriaDescricao, IFormFile Foto)
        {
            CategoriaProdutoView NovaCategoria = new CategoriaProdutoView();
            NovaCategoria.Nome = NomeCategoria;
            NovaCategoria.CategoriaDescricao = CategoriaDescricao;
            string path = $"wwwroot/Images/Categoria_{NovaCategoria.CategoriaID}";
            if (Foto is not null)
            {
                using var stream = new MemoryStream();
                Foto.CopyToAsync(stream);
                stream.Position = 0;
                using var fileStream = new FileStream($"{path}empresa_{NovaCategoria.CategoriaID}.png", FileMode.OpenOrCreate);
                stream.CopyTo(fileStream);
                fileStream.Close();
            }
            NovaCategoria.CategoriaFoto = $"{path}empresa_{NovaCategoria.CategoriaID}.png".Replace(@"wwwroot", string.Empty);

            categoria.InsertCategoria(NovaCategoria);
            return RedirectToAction("Index");

        }

        //atualizar

        [HttpGet]
        public IActionResult Atualizar(int id)
        {
            ViewBag.CategoriaAtualizar = categoria.getTodasCategorias().Where(x => x.CategoriaID == id).FirstOrDefault();
            return View();
        }

        [HttpPost]
        public IActionResult Atualizar(string NomeCategoria, string CategoriaDescricao, IFormFile CategoriaFoto, string codigo)
        {

            CategoriaProdutoView AtualizarCategoria = new CategoriaProdutoView();
            AtualizarCategoria.CategoriaID = Convert.ToInt32(codigo);
            AtualizarCategoria.Nome = NomeCategoria;
            AtualizarCategoria.CategoriaDescricao = CategoriaDescricao;

            string path = $"wwwroot/Images/Categoria_{AtualizarCategoria.CategoriaID}";
            if (CategoriaFoto is not null)
            {
                using var stream = new MemoryStream();
                CategoriaFoto.CopyToAsync(stream);
                stream.Position = 0;
                using var fileStream = new FileStream($"{path}empresa_{AtualizarCategoria.CategoriaID}.png", FileMode.OpenOrCreate);
                stream.CopyTo(fileStream);
            }
            AtualizarCategoria.CategoriaFoto = $"{path}empresa_{AtualizarCategoria.CategoriaID}.png".Replace(@"wwwroot", string.Empty);
            categoria.UptdateCategoria(AtualizarCategoria);

            return RedirectToAction("Index");
        }

        //apagar
        [HttpGet]
        public IActionResult Apagar(string id)
        {

            CategoriaProdutoView apagarCategoria = new CategoriaProdutoView();
            apagarCategoria.CategoriaID = Convert.ToInt32(id);
            categoria.ApagarCategoria(apagarCategoria);

            return RedirectToAction("Index");
        }
    }
}

Cardápio/src/CárdapioV3_Tunado/CárdapioV3_Tunado/Controllers/DashboardController.cs
using CárdapioV3_Tunado.DAL;
using CárdapioV3_Tunado.Models.enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CárdapioV3_Tunado.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly PedidosDAO _pedidosContext;
        private readonly ProdutoDAO _produtoContext;
        private readonly CategoriaDAO _categoriaContext;

        public DashboardController()
        {
            _pedidosContext = new PedidosDAO();
            _produtoContext = new ProdutoDAO();
            _categoriaContext = new CategoriaDAO();
        }

        public async Task <IActionResult> Index()
        {
            ViewBag.PedidosUltimos7Dias = (await _pedidosContext.getTodosPedidos(7, int.Parse(User.Identity!.Name!))).Count;
            ViewBag.PedidosUltimos15Dias = (await _pedidosContext.getTodosPedidos(15, int.Parse(User.Identity!.Name!))).Count;
            ViewBag.PedidosUltimos30Dias = (await _pedidosContext.getTodosPedidos(30, int.Parse(User.Identity!.Name!))).Count;
            ViewBag.QuantidadeProdutos = _produtoContext.getQtdProdutosbyEmpresa(int.Parse(User.Identity!.Name!));
            ViewBag.ProdutoMaisProcurado = _produtoContext.getMaisPedidos(int.Parse(User.Identity!.Name!)).FirstOrDefault();
            if (User.IsInRole(nameof(E_Perfil.MASTER)))
                ViewBag.QuantidadeCategorias = _categoriaContext.getTodasCategorias().Count;
            return View();
        }
    }
}

Cardápio/src/CárdapioV3_Tunado/CárdapioV3_Tunado/Controllers/ProdutoController.cs
using CárdapioV3_Tunado.DAL;
using CárdapioV3_Tunado.Models;
using CárdapioV3_Tunado.Models.enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CárdapioV3_Tunado.Controllers
{       
    [Authorize]
    public class ProdutoController : Controller
    {
        CardapioDAO cardapio = new CardapioDAO();
        ProdutoDAO produto = new ProdutoDAO();
        EmpresaDAO empresa = new EmpresaDAO();

        [Authorize]
        public IActionResult Index(int? EmpresaID)
        {
            if (User.IsInRole(nameof(E_Perfil.MASTER)) && EmpresaID != null)
            {
                ViewBag.listaProdutosController = cardapio.getTodosProdutosbyEmpresa(Convert.ToInt32(EmpresaID));
                ViewBag.NomeEmpresa = empresa.getTodasEmpresasbyID(Convert.ToInt32(EmpresaID));
                ViewBag.TodasEmpresasBox = empresa.getTodasEmpresas();
                ViewBag.EmpresaIDSubmit = EmpresaID;
                return View();
            }
            else
            {
                if (User.Identity!.Name is null) return RedirectToAction("/empresa/logar");
                var idEmpresa = int.Parse(User.Identity!.Name);
                ViewBag.listaProdutosController = cardapio.getTodosProdutosbyEmpresa(idEmpresa);
                ViewBag.todosProdutos = produto.SepararProdutos();
                ViewBag.NomeEmpresa = empresa.getTodasEmpresasbyID(idEmpresa);
                ViewBag.TodasEmpresasBox = empresa.getTodasEmpresas();
                return View();
            }
        }

        //create
        [HttpGet]
        [Authorize]
        public IActionResult create(int idEmpresa)
        {
            if (User.Identity!.Name is null) return RedirectToAction("/empresa/logar");
            CategoriaDAO cardapio = new CategoriaDAO();
            idEmpresa = int.Parse(User.Identity!.Name);
            ViewBag.listaCategorias = cardapio.getTodasCategorias();
            return View();

        }

        [HttpPost]
        [Authorize]
        public IActionResult create(string NomeProduto, string ProdutoDescricao, string NutricaoProduto, double PrecoProduto, int Categorias)
        {
            if (User.Identity!.Name is null) return RedirectToAction("/empresa/logar");
            int idEmpresa = int.Parse(User.Identity!.Name);
            CategoriaProdutoView NovoProduto = new CategoriaProdutoView();
            NovoProduto.NomeProduto = NomeProduto;
            NovoProduto.DescricaoProduto = ProdutoDescricao;
            NovoProduto.NutricaoProduto = NutricaoProduto;
            NovoProduto.PrecoProduto = PrecoProduto;
            NovoProduto.CategoriaID = Categorias;
            NovoProduto.EmpresaID = idEmpresa;
            produto.InsertProduto(NovoProduto);
            //int ID = produto.ProdutoIDRetornar();
            //var CookieOptions = new CookieOptions
            //{
            //    Expires = DateTime.Now.AddSeconds(50)
            //};
            //Response.Cookies.Append("IDProduto", ID.ToString(), CookieOptions);
            return RedirectToAction("Index");

        }

        //atualizar

        [HttpGet]
        public async Task <IActionResult> Atualizar(int id)
        {
            CategoriaDAO categoria = new CategoriaDAO();
            ViewBag.ProdutoAtualizar = (await produto.getTodosProdutos()).FirstOrDefault(x => x.ProID == id);
            ViewBag.Categoria = categoria.getTodasCategorias();
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Atualizar(string NomeProduto, string DescricaoProduto, string NutricaoProduto, string codigo, double PrecoProduto, int CategoriaID, int EmpresaID)
        {
            if (User.Identity!.Name is null) return RedirectToAction("/empresa/logar");
            EmpresaID = int.Parse(User.Identity!.Name);
            CategoriaProdutoView AtualizarProduto = new CategoriaProdutoView();
            AtualizarProduto.ProID = Convert.ToInt32(codigo);
            AtualizarProduto.NomeProduto = NomeProduto;
            AtualizarProduto.DescricaoProduto = DescricaoProduto;
            AtualizarProduto.NutricaoProduto = NutricaoProduto;
            AtualizarProduto.PrecoProduto = PrecoProduto;
            AtualizarProduto.CategoriaID = CategoriaID;
            AtualizarProduto.EmpresaID = EmpresaID;
            produto.UptdateProduto(AtualizarProduto);

            return RedirectToAction("Index");
        }

        //apagar
        [HttpGet]
        public IActionResult Apagar(string id)
        {

            CategoriaProdutoView apagarProduto = new CategoriaProdutoView();
            apagarProduto.ProID = Convert.ToInt32(id);
            produto.ApagarProduto(apagarProduto);

            return RedirectToAction("Index");
        }
    }
}

Cardápio/src/CárdapioV3_Tunado/CárdapioV3_Tunado/Views/Shared/_Layout.cshtml
@using CárdapioV3_Tunado.Models.enums
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CárdapioV3_Tunado</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CárdapioV3_Tunado.styles.css" asp-append-version="true" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>


</head>
<body>
    <div class="container">
        @if (User.Identity!.IsAuthenticated)
        {
            <nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark" data-bs-theme="dark">
                <div class="container-fluid">

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon text-white">Menu</span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Cardapio" asp-action="Index">Cardápio</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/Empresa/Index?idEmpresa=">Empresa</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" asp-controller="Produto" asp-action="Index">Produtos</a>
                            </li>

                            @if (User.IsInRole(nameof(E_Perfil.MASTER)))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Categoria" asp-action="Index">Categorias</a>
                                </li>
                            }

                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                            </li>

                            <li class="nav-item">
                                <form method="post" asp-controller="Empresa" asp-action="Logout">
                                    <a class="nav-link" href="#" onclick="document.forms[0].submit()">Logout</a>
                                </form>
                            </li>

                            <li class="nav-item">
                                <form method="post" asp-controller="Empresa" asp-action="Logout">
                                    <a class="nav-link" href="#" >Version 1.04</a>
                                </form>
                            </li>

                            

                        </ul>
                    </div>
                </div>
            </nav>


        }
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


          
       


       
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)



    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>



    <script>
        $(document).ready(function () {
            $('#telefone').mask('+99(99)99999-9999');
            $('#cnpj').mask('99.999.999/9999-99');
        });
    </script>

</body>
</html>